use crate::{
    client::{Error as ClientError, GeminiClient},
    files::model::File,
};
use std::sync::Arc;

/// A handle to a file on the Gemini API.
pub struct GeminiFile {
    inner: File,
    client: Arc<GeminiClient>,
}

impl GeminiFile {
    pub(crate) fn new(client: Arc<GeminiClient>, inner: File) -> Self {
        Self { inner, client }
    }

    pub fn name(&self) -> &str {
        &self.inner.name
    }

    /// Delete the file.
    pub async fn delete(self) -> Result<(), (Self, ClientError)> {
        match self.client.delete_file(&self.inner.name).await {
            Ok(_) => Ok(()),
            Err(e) => Err((self, e)),
        }
    }

    /// Get the file metadata.
    pub fn get_file_meta(&self) -> &File {
        &self.inner
    }

    /// Download the file.
    ///
    /// Work only for files that was generated by Gemini.
    pub async fn download(&self) -> Result<Vec<u8>, ClientError> {
        self.client.download_file(self.name()).await
    }
}
