use snafu::ResultExt;
use std::sync::Arc;

use super::*;
use crate::client::GeminiClient;

/// A handle to a file on the Gemini API.
pub struct FileHandle {
    inner: super::model::File,
    client: Arc<GeminiClient>,
}

impl FileHandle {
    pub(crate) fn new(client: Arc<GeminiClient>, inner: super::model::File) -> Self {
        Self { inner, client }
    }

    pub fn name(&self) -> &str {
        &self.inner.name
    }

    /// Get the file metadata.
    pub fn get_file_meta(&self) -> &super::model::File {
        &self.inner
    }

    /// Delete the file.
    pub async fn delete(self) -> Result<(), (Self, Error)> {
        match self
            .client
            .delete_file(&self.inner.name)
            .await
            .context(ClientSnafu)
        {
            Ok(_) => Ok(()),
            Err(e) => Err((self, e)),
        }
    }

    /// Download the file content.
    ///
    /// **Important**: Only files **generated by the Gemini API** can be downloaded.
    /// This includes:
    /// - Images generated via image generation APIs
    /// - Audio files generated via text-to-speech APIs
    /// - Other content created by the model
    ///
    /// Files **uploaded by users** (via `create_file()`) **cannot be downloaded**.
    /// Attempting to download an uploaded file will result in a 400 error:
    /// "Only GENERATED files can be downloaded."
    ///
    /// You can check if a file is downloadable using [`is_downloadable()`](Self::is_downloadable).
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The file is not a generated file (uploaded files cannot be downloaded)
    /// - Network or API errors occur
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use gemini_rust::Gemini;
    /// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
    /// # let gemini = Gemini::new("api-key")?;
    /// // Only works for generated files
    /// let file = gemini.get_file("files/generated-image-123").await?;
    /// if file.is_downloadable() {
    ///     let content = file.download().await?;
    ///     println!("Downloaded {} bytes", content.len());
    /// }
    /// # Ok(())
    /// # }
    /// ```
    pub async fn download(&self) -> Result<Vec<u8>, Error> {
        self.client
            .download_file(self.name())
            .await
            .context(ClientSnafu)
    }

    /// Check if this file can be downloaded.
    ///
    /// Returns `true` if the file is a generated file (has a `download_uri`).
    /// Only generated files can be downloaded; uploaded files cannot.
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use gemini_rust::Gemini;
    /// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
    /// # let gemini = Gemini::new("api-key")?;
    /// let file = gemini.get_file("files/some-file").await?;
    /// if file.is_downloadable() {
    ///     println!("File can be downloaded");
    ///     let content = file.download().await?;
    /// } else {
    ///     println!("File cannot be downloaded (it's an uploaded file)");
    /// }
    /// # Ok(())
    /// # }
    /// ```
    pub fn is_downloadable(&self) -> bool {
        self.inner.download_uri.is_some()
    }
}
